# Generated by Django 3.1.5 on 2021-02-01 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0003_auto_20210201_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(related_name='project_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
