# Generated by Django 3.1.5 on 2021-02-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_project_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='likes',
        ),
    ]
