# Generated by Django 3.1.5 on 2021-02-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20210203_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='body',
        ),
        migrations.RemoveField(
            model_name='project',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_tag',
        ),
    ]
