# Generated by Django 3.1.5 on 2021-02-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='gmail',
            new_name='email',
        ),
    ]
